# Generated by Django 3.2 on 2021-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='isemployer',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='isjobseeker',
        ),
        migrations.AddField(
            model_name='employer',
            name='accounttype',
            field=models.CharField(default='employer', max_length=200),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='accounttype',
            field=models.CharField(default='jobseeker', max_length=200),
        ),
    ]
