# Generated by Django 3.2 on 2021-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210624_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
