# Generated by Django 3.2 on 2021-06-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='durationperday',
            new_name='duration_per_day',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jobtype',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='operationtype',
            new_name='operation_type',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salaryperannum',
            new_name='salary_in_LPA',
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
