# Generated by Django 3.2 on 2021-06-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210627_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='accounttype',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='accounttype',
        ),
    ]
