# Generated by Django 3.2 on 2021-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='designation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
