# Generated by Django 3.2 on 2021-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employer_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='isapplied',
            field=models.BooleanField(default=True),
        ),
    ]
