# Generated by Django 3.2 on 2021-06-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_application_isapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='isapplied',
            field=models.BooleanField(default=False),
        ),
    ]
