# Generated by Django 3.2 on 2021-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_application_isapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
