# Generated by Django 3.2 on 2021-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210701_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
